spring:
  application:
    name: life-and-money-api
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false


logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug